package keyval

import (
	"fmt"
	"math/big"

	"github.com/pkg/errors"
)

// A TupleErrorMode is passed to ReadTuple and
// modifies the way ReadTuple fails.
type TupleErrorMode = int

const (
	// AllErrors tells ReadTuple to check for
	// a LongTupleError.
	AllErrors TupleErrorMode = iota

	// AllowLong tells ReadTuple to not check
	// for a LongTupleError.
	AllowLong
)

// A ConversionError is returned by ReadTuple when
// the TupleIterator fails to convert a Tuple element
// to the requested type.
type ConversionError struct {
	InValue interface{}
	OutType interface{}
	Index   int
}

func (t ConversionError) Error() string {
	return fmt.Sprintf("failed to convert element %d from %v to %T", t.Index, t.InValue, t.OutType)
}

var (
	// ShortTupleError is returned by ReadTuple when the TupleIterator
	// reads beyond the length of the Tuple.
	ShortTupleError = errors.New("read past end of tuple")

	// LongTupleError is returned by ReadTuple when the entire Tuple
	// is not consumed. This error isn't returned when ReadTuple is
	// given the AllowLong flag.
	LongTupleError = errors.New("did not parse entire tuple")
)

// ReadTuple provides a way to iterate over a Tuple's elements and convert each element to it's
// expected type. The caller-provided function uses a TupleIterator to read each of the Tuple's
// elements is sequential order. Any errors generated by the caller-provided function are returned
// as is. Additionally, ReadTuple may return ShortTupleError, LongTupleError, or an instance of
// ConversionError. See these errors for more information on when they are returned.
func ReadTuple(t Tuple, mode TupleErrorMode, f func(*TupleIterator) error) (err error) {
	defer func() {
		if e := recover(); e != nil {
			if e, ok := e.(ConversionError); ok {
				err = e
				return
			}
			if e == ShortTupleError {
				err = ShortTupleError
				return
			}
			panic(e)
		}
	}()

	p := TupleIterator{t: t}
	if err := f(&p); err != nil {
		return err
	}

	if mode == AllErrors && p.i != len(t) {
		return LongTupleError
	}
	return nil
}

// TupleIterator provides methods for reading each Tuple element
// and converting the read element to an expected type. It is
// meant to be created by the ReadTuple function. For more
// information, see the ReadTuple documentation.
type TupleIterator struct {
	t Tuple
	i int
}

func (i *TupleIterator) getIndex() int {
	if i.i >= len(i.t) {
		panic(ShortTupleError)
	}

	i.i++
	return i.i - 1
}

func (i *TupleIterator) Any() TupElement {
	return i.t[i.getIndex()]
}

func (i *TupleIterator) Bool() (out Bool, err error) {
	index := i.getIndex()
	if val, ok := i.t[index].(Bool); ok {
		return val, nil
	}
	return false, ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	}
}

func (i *TupleIterator) MustBool() Bool {
	val, err := i.Bool()
	if err != nil {
		panic(err)
	}
	return val
}

func (i *TupleIterator) Int() (out Int, err error) {
	index := i.getIndex()
	if val, ok := i.t[index].(Int); ok {
		return val, nil
	}
	return 0, ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	}
}

func (i *TupleIterator) MustInt() Int {
	val, err := i.Int()
	if err != nil {
		panic(err)
	}
	return val
}

func (i *TupleIterator) Uint() (out Uint, err error) {
	index := i.getIndex()
	if val, ok := i.t[index].(Uint); ok {
		return val, nil
	}
	return 0, ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	}
}

func (i *TupleIterator) MustUint() Uint {
	val, err := i.Uint()
	if err != nil {
		panic(err)
	}
	return val
}

func (i *TupleIterator) BigInt() (out BigInt, err error) {
	index := i.getIndex()
	if val, ok := i.t[index].(Int); ok {
		return BigInt(*big.NewInt(int64(val))), nil
	}
	if val, ok := i.t[index].(Uint); ok {
		bi := big.NewInt(0)
		bi.SetUint64(uint64(val))
		return BigInt(*bi), nil
	}
	if val, ok := i.t[index].(BigInt); ok {
		return val, nil
	}
	return BigInt{}, ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	}
}

func (i *TupleIterator) MustBigInt() BigInt {
	val, err := i.BigInt()
	if err != nil {
		panic(err)
	}
	return val
}

func (i *TupleIterator) Float() (out Float, err error) {
	index := i.getIndex()
	if val, ok := i.t[index].(Float); ok {
		return val, nil
	}
	return 0, ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	}
}

func (i *TupleIterator) MustFloat() Float {
	val, err := i.Float()
	if err != nil {
		panic(err)
	}
	return val
}

func (i *TupleIterator) String() (out String, err error) {
	index := i.getIndex()
	if val, ok := i.t[index].(String); ok {
		return val, nil
	}
	return "", ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	}
}

func (i *TupleIterator) MustString() String {
	val, err := i.String()
	if err != nil {
		panic(err)
	}
	return val
}

func (i *TupleIterator) Bytes() (out Bytes, err error) {
	index := i.getIndex()
	if val, ok := i.t[index].(Bytes); ok {
		return val, nil
	}
	return nil, ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	}
}

func (i *TupleIterator) MustBytes() Bytes {
	val, err := i.Bytes()
	if err != nil {
		panic(err)
	}
	return val
}

func (i *TupleIterator) UUID() (out UUID, err error) {
	index := i.getIndex()
	if val, ok := i.t[index].(UUID); ok {
		return val, nil
	}
	return UUID{}, ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	}
}

func (i *TupleIterator) MustUUID() UUID {
	val, err := i.UUID()
	if err != nil {
		panic(err)
	}
	return val
}

func (i *TupleIterator) Tuple() (out Tuple, err error) {
	index := i.getIndex()
	if val, ok := i.t[index].(Tuple); ok {
		return val, nil
	}
	return nil, ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	}
}

func (i *TupleIterator) MustTuple() Tuple {
	val, err := i.Tuple()
	if err != nil {
		panic(err)
	}
	return val
}
