// Code generated by visitor -visitor ValueVisitor -acceptor value -types Tuple,Nil,Int,Uint,Bool,Float,String,UUID,Bytes,Variable,Clear. DO NOT EDIT.
package keyval

type (
	ValueVisitor interface {
		VisitTuple(Tuple)
		VisitNil(Nil)
		VisitInt(Int)
		VisitUint(Uint)
		VisitBool(Bool)
		VisitFloat(Float)
		VisitString(String)
		VisitUUID(UUID)
		VisitBytes(Bytes)
		VisitVariable(Variable)
		VisitClear(Clear)
	}

	value interface {
		Value(ValueVisitor)
	}
)

func _() {
	var (
		Tuple_    Tuple
		Nil_      Nil
		Int_      Int
		Uint_     Uint
		Bool_     Bool
		Float_    Float
		String_   String
		UUID_     UUID
		Bytes_    Bytes
		Variable_ Variable
		Clear_    Clear

		_ value = &Tuple_
		_ value = &Nil_
		_ value = &Int_
		_ value = &Uint_
		_ value = &Bool_
		_ value = &Float_
		_ value = &String_
		_ value = &UUID_
		_ value = &Bytes_
		_ value = &Variable_
		_ value = &Clear_
	)
}

func (x Tuple) Value(v ValueVisitor) {
	v.VisitTuple(x)
}

func (x Nil) Value(v ValueVisitor) {
	v.VisitNil(x)
}

func (x Int) Value(v ValueVisitor) {
	v.VisitInt(x)
}

func (x Uint) Value(v ValueVisitor) {
	v.VisitUint(x)
}

func (x Bool) Value(v ValueVisitor) {
	v.VisitBool(x)
}

func (x Float) Value(v ValueVisitor) {
	v.VisitFloat(x)
}

func (x String) Value(v ValueVisitor) {
	v.VisitString(x)
}

func (x UUID) Value(v ValueVisitor) {
	v.VisitUUID(x)
}

func (x Bytes) Value(v ValueVisitor) {
	v.VisitBytes(x)
}

func (x Variable) Value(v ValueVisitor) {
	v.VisitVariable(x)
}

func (x Clear) Value(v ValueVisitor) {
	v.VisitClear(x)
}

