volumes:
  cache:

services:

  # The build service is responsible for building,
  # linting, and testing the code.
  build:
    container_name: "build"
    image: "docker.io/janderland/fql-build:${DOCKER_TAG}"
    platform: "linux/amd64"
    build:
      context: "./docker"
      target: "builder"
      platforms:
        - "linux/amd64"
      args: &build_args
        FQL_VER: "${DOCKER_TAG}"
        FDB_LIB_URL: "${FDB_LIB_URL}"
        GO_URL: "${GO_URL}"
        GOLANGCI_LINT_VER: "${GOLANGCI_LINT_VER}"
        SHELLCHECK_URL: "${SHELLCHECK_URL}"
        HADOLINT_URL: "${HADOLINT_URL}"
        JQ_URL: "${JQ_URL}"
        PANDOC_URL: "${PANDOC_URL}"
    depends_on:
      - "fdb"
    working_dir: "/fql"
    volumes:
      - ".:/fql"
      - "cache:/cache"

  # The fql service allows us to build and test the
  # fql Docker image.
  fql:
    container_name: "fql"
    image: "docker.io/janderland/fql:${DOCKER_TAG}"
    platform: "linux/amd64"
    build:
      context: "."
      dockerfile: "./docker/Dockerfile"
      platforms:
        - "linux/amd64"
      args: *build_args
    depends_on:
      - "fdb"

  # The fdb service provides a single-node cluster
  # for integration testing.
  fdb:
    container_name: "fdb"
    image: "${FDB_DOCKER_IMAGE}"
    platform: "linux/amd64"
    ports:
      - "4500:4500"
