package keyval

import (
	"fmt"
	"math/big"

	"github.com/apple/foundationdb/bindings/go/src/fdb"

	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	"github.com/pkg/errors"
)

// A TupleErrorMode is passed to ReadTuple and
// modifies the way ReadTuple fails.
type TupleErrorMode = int

const (
	// AllErrors tells ReadTuple to check for
	// a LongTupleError.
	AllErrors TupleErrorMode = iota

	// AllowLong tells ReadTuple to not check
	// for a LongTupleError.
	AllowLong
)

// A ConversionError is returned by ReadTuple when
// the TupleIterator fails to convert a Tuple element
// to the requested type.
type ConversionError struct {
	InValue interface{}
	OutType interface{}
	Index   int
}

func (t ConversionError) Error() string {
	return fmt.Sprintf("failed to convert element %d from %v to %T", t.Index, t.InValue, t.OutType)
}

var (
	// ShortTupleError is returned by ReadTuple when the TupleIterator
	// reads beyond the length of the Tuple.
	ShortTupleError = errors.New("read past end of tuple")

	// LongTupleError is returned by ReadTuple when the entire Tuple
	// is not consumed. This error isn't returned when ReadTuple is
	// given the AllowLong flag.
	LongTupleError = errors.New("did not parse entire tuple")
)

// ReadTuple provides a way to iterate over a Tuple's elements and convert each element to it's
// expected type. The caller-provided function uses a TupleIterator to read each of the Tuple's
// elements is sequential order. Any errors generated by the caller-provided function are returned
// as is. Additionally, ReadTuple may return ShortTupleError, LongTupleError, or an instance of
// ConversionError. See these errors for more information on when they are returned.
func ReadTuple(t Tuple, mode TupleErrorMode, f func(*TupleIterator) error) (err error) {
	defer func() {
		if e := recover(); e != nil {
			if e, ok := e.(ConversionError); ok {
				err = e
				return
			}
			if e == ShortTupleError {
				err = ShortTupleError
				return
			}
			panic(e)
		}
	}()

	p := TupleIterator{t: t}
	if err := f(&p); err != nil {
		return err
	}

	if mode == AllErrors && p.i != len(t) {
		return LongTupleError
	}
	return nil
}

// TupleIterator provides methods for reading each Tuple element
// and converting the read element to an expected type. It is
// meant to be created by the ReadTuple function. For more
// information, see the ReadTuple documentation.
type TupleIterator struct {
	t Tuple
	i int
}

func (i *TupleIterator) getIndex() int {
	if i.i >= len(i.t) {
		panic(ShortTupleError)
	}

	i.i++
	return i.i - 1
}

func (i *TupleIterator) Any() interface{} {
	return i.t[i.getIndex()]
}

func (i *TupleIterator) Bool() (out bool) {
	index := i.getIndex()
	if val, ok := i.t[index].(bool); ok {
		return val
	}
	panic(ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	})
}

func (i *TupleIterator) Int() (out int64) {
	index := i.getIndex()
	if val, ok := i.t[index].(int64); ok {
		return val
	}
	if val, ok := i.t[index].(int); ok {
		return int64(val)
	}
	panic(ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	})
}

func (i *TupleIterator) Uint() (out uint64) {
	index := i.getIndex()
	if val, ok := i.t[index].(int64); ok {
		return uint64(val)
	}
	if val, ok := i.t[index].(uint64); ok {
		return val
	}
	if val, ok := i.t[index].(int); ok {
		return uint64(val)
	}
	if val, ok := i.t[index].(uint); ok {
		return uint64(val)
	}
	panic(ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	})
}

func (i *TupleIterator) BigInt() (out *big.Int) {
	index := i.getIndex()
	if val, ok := i.t[index].(int64); ok {
		return big.NewInt(val)
	}
	if val, ok := i.t[index].(int); ok {
		return big.NewInt(int64(val))
	}
	if val, ok := i.t[index].(uint64); ok {
		out = big.NewInt(0)
		out.SetUint64(val)
		return out
	}
	if val, ok := i.t[index].(uint); ok {
		out = big.NewInt(0)
		out.SetUint64(uint64(val))
		return out
	}
	if val, ok := i.t[index].(big.Int); ok {
		return &val
	}
	if val, ok := i.t[index].(*big.Int); ok {
		return val
	}
	panic(ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	})
}

func (i *TupleIterator) Float() (out float64) {
	index := i.getIndex()
	if val, ok := i.t[index].(float64); ok {
		return val
	}
	if val, ok := i.t[index].(float32); ok {
		return float64(val)
	}
	panic(ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	})
}

func (i *TupleIterator) String() (out string) {
	index := i.getIndex()
	if val, ok := i.t[index].(string); ok {
		return val
	}
	panic(ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	})
}

func (i *TupleIterator) Bytes() (out []byte) {
	index := i.getIndex()
	if val, ok := i.t[index].([]byte); ok {
		return val
	}
	if val, ok := i.t[index].(fdb.KeyConvertible); ok {
		return val.FDBKey()
	}
	panic(ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	})
}

func (i *TupleIterator) UUID() (out UUID) {
	index := i.getIndex()
	if val, ok := i.t[index].(UUID); ok {
		return val
	}
	panic(ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	})
}

func (i *TupleIterator) Tuple() (out Tuple) {
	index := i.getIndex()
	if val, ok := i.t[index].(Tuple); ok {
		return val
	}
	if val, ok := i.t[index].(tuple.Tuple); ok {
		return FromFDBTuple(val)
	}
	panic(ConversionError{
		InValue: i.t[index],
		OutType: out,
		Index:   index,
	})
}
