// Code generated by visitor -op-name Directory -param-name DirElement -types String,Variable. DO NOT EDIT.
package keyval

type (
	DirectoryOperation interface {
		ForString(String)
		ForVariable(Variable)
	}

	DirElement interface {
		DirElement(DirectoryOperation)
		Eq(interface{}) bool
	}
)

func _() {
	var (
		String   String
		Variable Variable

		_ DirElement = &String
		_ DirElement = &Variable
	)
}

func (x String) DirElement(op DirectoryOperation) {
	op.ForString(x)
}

func (x Variable) DirElement(op DirectoryOperation) {
	op.ForVariable(x)
}

