// Code generated by: operation -op-name Query -param-name query -types Directory,Key,KeyValue. DO NOT EDIT.

package keyval

type (
	QueryOperation interface {
		// ForDirectory performs the QueryOperation if the given query is of type Directory.
		ForDirectory(Directory)
		// ForKey performs the QueryOperation if the given query is of type Key.
		ForKey(Key)
		// ForKeyValue performs the QueryOperation if the given query is of type KeyValue.
		ForKeyValue(KeyValue)
	}

	query interface {
		// Query executes the given QueryOperation on this query.
		Query(QueryOperation)

		// Eq returns true if the given value is equal to this query.
		Eq(interface{}) bool
	}
)

func _() {
	var (
		Directory Directory
		Key       Key
		KeyValue  KeyValue

		_ query = &Directory
		_ query = &Key
		_ query = &KeyValue
	)
}

func (x Directory) Query(op QueryOperation) {
	op.ForDirectory(x)
}

func (x Key) Query(op QueryOperation) {
	op.ForKey(x)
}

func (x KeyValue) Query(op QueryOperation) {
	op.ForKeyValue(x)
}

