// Code generated by operation -op-name Query -param-name query -types Directory,Key,KeyValue. DO NOT EDIT.
package keyval

type (
	QueryOperation interface {
		ForDirectory(Directory)
		ForKey(Key)
		ForKeyValue(KeyValue)
	}

	query interface {
		Query(QueryOperation)
		Eq(interface{}) bool
	}
)

func _() {
	var (
		Directory Directory
		Key       Key
		KeyValue  KeyValue

		_ query = &Directory
		_ query = &Key
		_ query = &KeyValue
	)
}

func (x Directory) Query(op QueryOperation) {
	op.ForDirectory(x)
}

func (x Key) Query(op QueryOperation) {
	op.ForKey(x)
}

func (x KeyValue) Query(op QueryOperation) {
	op.ForKeyValue(x)
}

